namespace FFLSharp.Interop
{
    public enum FFLiEyebrowTextureType
    {
        FFLI_EYEBROW_TEXTURE_TYPE_0 = 0,
        FFLI_EYEBROW_TEXTURE_TYPE_13 = 13,
        FFLI_EYEBROW_TEXTURE_TYPE_24 = 24,
        FFLI_EYEBROW_TEXTURE_TYPE_25 = 25,
        FFLI_EYEBROW_TEXTURE_TYPE_26 = 26,
        FFLI_EYEBROW_TEXTURE_TYPE_27 = 27,
        FFLI_EYEBROW_TEXTURE_TYPE_MAX = 28,
    }
}
