namespace FFLSharp.Interop
{
    [NativeTypeName("unsigned int")]
    public enum FFLiEyeTextureType : uint
    {
        FFLI_EYE_TEXTURE_TYPE_0 = 0,
        FFLI_EYE_TEXTURE_TYPE_1 = 1,
        FFLI_EYE_TEXTURE_TYPE_2 = 2,
        FFLI_EYE_TEXTURE_TYPE_3 = 3,
        FFLI_EYE_TEXTURE_TYPE_4 = 4,
        FFLI_EYE_TEXTURE_TYPE_5 = 5,
        FFLI_EYE_TEXTURE_TYPE_6 = 6,
        FFLI_EYE_TEXTURE_TYPE_7 = 7,
        FFLI_EYE_TEXTURE_TYPE_8 = 8,
        FFLI_EYE_TEXTURE_TYPE_9 = 9,
        FFLI_EYE_TEXTURE_TYPE_10 = 10,
        FFLI_EYE_TEXTURE_TYPE_11 = 11,
        FFLI_EYE_TEXTURE_TYPE_12 = 12,
        FFLI_EYE_TEXTURE_TYPE_13 = 13,
        FFLI_EYE_TEXTURE_TYPE_14 = 14,
        FFLI_EYE_TEXTURE_TYPE_15 = 15,
        FFLI_EYE_TEXTURE_TYPE_16 = 16,
        FFLI_EYE_TEXTURE_TYPE_17 = 17,
        FFLI_EYE_TEXTURE_TYPE_18 = 18,
        FFLI_EYE_TEXTURE_TYPE_19 = 19,
        FFLI_EYE_TEXTURE_TYPE_20 = 20,
        FFLI_EYE_TEXTURE_TYPE_21 = 21,
        FFLI_EYE_TEXTURE_TYPE_22 = 22,
        FFLI_EYE_TEXTURE_TYPE_23 = 23,
        FFLI_EYE_TEXTURE_TYPE_24 = 24,
        FFLI_EYE_TEXTURE_TYPE_25 = 25,
        FFLI_EYE_TEXTURE_TYPE_26 = 26,
        FFLI_EYE_TEXTURE_TYPE_27 = 27,
        FFLI_EYE_TEXTURE_TYPE_28 = 28,
        FFLI_EYE_TEXTURE_TYPE_MAX = 29,
    }
}
